services:
  web:
    build: .
    network_mode: "host"
    environment:
      - TZ=Asia/Taipei
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongodb

  scraper:
    build: .
    environment:
      - TZ=Asia/Taipei
    volumes:
      - .:/app
    depends_on:
      - mongodb
    working_dir: /app
    command: ["python3", "/app/music_events/scripts/scraper.py"]
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
